// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module neureka_regif #(
        parameter ID_WIDTH = 1
    ) (
        input wire clk,
        input wire arst_n,

        input wire s_obi_req,
        output logic s_obi_gnt,
        input wire [6:0] s_obi_addr,
        input wire s_obi_we,
        input wire [3:0] s_obi_be,
        input wire [31:0] s_obi_wdata,
        input wire [ID_WIDTH-1:0] s_obi_aid,
        output logic s_obi_rvalid,
        input wire s_obi_rready,
        output logic [31:0] s_obi_rdata,
        output logic s_obi_err,
        output logic [ID_WIDTH-1:0] s_obi_rid,

        input neureka_regif_pkg::neureka_regif__in_t hwif_in,
        output neureka_regif_pkg::neureka_regif__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [6:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    // State & holding regs
    logic is_active; // A request is being served (not yet fully responded)
    logic gnt_q; // one-cycle grant for A-channel
    logic rsp_pending; // response ready but not yet accepted by manager
    logic [31:0] rsp_rdata_q;
    logic rsp_err_q;
    logic [$bits(s_obi_rid)-1:0] rid_q;

    // Latch AID on accept to echo back the response
    always_ff @(posedge clk or negedge arst_n) begin
        if (~arst_n) begin
            is_active <= 1'b0;
            gnt_q <= 1'b0;
            rsp_pending <= 1'b0;
            rsp_rdata_q <= '0;
            rsp_err_q <= 1'b0;
            rid_q <= '0;

            cpuif_req <= '0;
            cpuif_req_is_wr <= '0;
            cpuif_addr <= '0;
            cpuif_wr_data <= '0;
            cpuif_wr_biten <= '0;
        end else begin
            // defaults
            cpuif_req <= 1'b0;
            gnt_q <= s_obi_req & ~is_active;

            // Accept new request when idle
            if (~is_active) begin
                if (s_obi_req) begin
                    is_active <= 1'b1;
                    cpuif_req <= 1'b1;
                    cpuif_req_is_wr <= s_obi_we;
                    cpuif_addr <= {s_obi_addr[6:2], 2'b0};
                    cpuif_wr_data <= s_obi_wdata;
                    rid_q <= s_obi_aid;
                    for (int i = 0; i < 4; i++) begin
                        cpuif_wr_biten[i*8 +: 8] <= {8{ s_obi_be[i] }};
                    end
                end
            end

            // Capture response
            if (is_active && (cpuif_rd_ack || cpuif_wr_ack)) begin
                rsp_pending <= 1'b1;
                rsp_rdata_q <= cpuif_rd_data;
                rsp_err_q <= cpuif_rd_err | cpuif_wr_err;
                // NOTE: Keep 'is_active' asserted until the external R handshake completes
            end

            // Complete external R-channel handshake only if manager ready
            if (rsp_pending && s_obi_rvalid && s_obi_rready) begin
                rsp_pending <= 1'b0;
                is_active <= 1'b0; // free to accept the next request
            end
        end
    end

    // R-channel outputs (held stable while rsp_pending=1)
    assign s_obi_rvalid = rsp_pending;
    assign s_obi_rdata = rsp_rdata_q;
    assign s_obi_err = rsp_err_q;
    assign s_obi_rid = rid_q;

    // A-channel grant (registered one-cycle pulse when we accept a request)
    assign s_obi_gnt = gnt_q;

    logic cpuif_req_masked;

    // Read & write latencies are balanced. Stalls not required
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = '0;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            logic commit_trigger;
            logic acquire;
            logic reserved0;
            logic status;
            logic running_job;
            logic soft_clear;
            logic reserved1;
            logic reserved2;
        } hwpe_ctrl;
        struct {
            logic weights_ptr;
            logic infeat_ptr;
            logic outfeat_ptr;
            logic scale_ptr;
            logic scale_shift_ptr;
            logic scale_bias_ptr;
            logic infeat_d0_stride;
            logic infeat_d1_stride;
            logic infeat_d2_stride;
            logic outfeat_d0_stride;
            logic outfeat_d1_stride;
            logic outfeat_d2_stride;
            logic weights_d0_stride;
            logic weights_d1_stride;
            logic weights_d2_stride;
            logic subtile_rem0;
            logic subtile_rem1;
            logic subtile_rem2;
            logic subtile_nb0;
            logic subtile_nb1;
            logic padding;
            logic weight_offset;
            logic filter_mask;
            logic config0;
        } hwpe_job_dep;
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_err;
    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        automatic logic is_valid_addr;
        automatic logic is_invalid_rw;
        is_valid_addr = '1; // No error checking on valid address access
        is_invalid_rw = '0;
        decoded_reg_strb.hwpe_ctrl.commit_trigger = cpuif_req_masked & (cpuif_addr == 7'h0);
        decoded_reg_strb.hwpe_ctrl.acquire = cpuif_req_masked & (cpuif_addr == 7'h4) & !cpuif_req_is_wr;
        decoded_reg_strb.hwpe_ctrl.reserved0 = cpuif_req_masked & (cpuif_addr == 7'h8) & !cpuif_req_is_wr;
        decoded_reg_strb.hwpe_ctrl.status = cpuif_req_masked & (cpuif_addr == 7'hc) & !cpuif_req_is_wr;
        decoded_reg_strb.hwpe_ctrl.running_job = cpuif_req_masked & (cpuif_addr == 7'h10) & !cpuif_req_is_wr;
        decoded_reg_strb.hwpe_ctrl.soft_clear = cpuif_req_masked & (cpuif_addr == 7'h14);
        decoded_reg_strb.hwpe_ctrl.reserved1 = cpuif_req_masked & (cpuif_addr == 7'h18) & !cpuif_req_is_wr;
        decoded_reg_strb.hwpe_ctrl.reserved2 = cpuif_req_masked & (cpuif_addr == 7'h1c) & !cpuif_req_is_wr;
        decoded_reg_strb.hwpe_job_dep.weights_ptr = cpuif_req_masked & (cpuif_addr == 7'h20);
        decoded_reg_strb.hwpe_job_dep.infeat_ptr = cpuif_req_masked & (cpuif_addr == 7'h24);
        decoded_reg_strb.hwpe_job_dep.outfeat_ptr = cpuif_req_masked & (cpuif_addr == 7'h28);
        decoded_reg_strb.hwpe_job_dep.scale_ptr = cpuif_req_masked & (cpuif_addr == 7'h2c);
        decoded_reg_strb.hwpe_job_dep.scale_shift_ptr = cpuif_req_masked & (cpuif_addr == 7'h30);
        decoded_reg_strb.hwpe_job_dep.scale_bias_ptr = cpuif_req_masked & (cpuif_addr == 7'h34);
        decoded_reg_strb.hwpe_job_dep.infeat_d0_stride = cpuif_req_masked & (cpuif_addr == 7'h38);
        decoded_reg_strb.hwpe_job_dep.infeat_d1_stride = cpuif_req_masked & (cpuif_addr == 7'h3c);
        decoded_reg_strb.hwpe_job_dep.infeat_d2_stride = cpuif_req_masked & (cpuif_addr == 7'h40);
        decoded_reg_strb.hwpe_job_dep.outfeat_d0_stride = cpuif_req_masked & (cpuif_addr == 7'h44);
        decoded_reg_strb.hwpe_job_dep.outfeat_d1_stride = cpuif_req_masked & (cpuif_addr == 7'h48);
        decoded_reg_strb.hwpe_job_dep.outfeat_d2_stride = cpuif_req_masked & (cpuif_addr == 7'h4c);
        decoded_reg_strb.hwpe_job_dep.weights_d0_stride = cpuif_req_masked & (cpuif_addr == 7'h50);
        decoded_reg_strb.hwpe_job_dep.weights_d1_stride = cpuif_req_masked & (cpuif_addr == 7'h54);
        decoded_reg_strb.hwpe_job_dep.weights_d2_stride = cpuif_req_masked & (cpuif_addr == 7'h58);
        decoded_reg_strb.hwpe_job_dep.subtile_rem0 = cpuif_req_masked & (cpuif_addr == 7'h5c);
        decoded_reg_strb.hwpe_job_dep.subtile_rem1 = cpuif_req_masked & (cpuif_addr == 7'h60);
        decoded_reg_strb.hwpe_job_dep.subtile_rem2 = cpuif_req_masked & (cpuif_addr == 7'h64);
        decoded_reg_strb.hwpe_job_dep.subtile_nb0 = cpuif_req_masked & (cpuif_addr == 7'h68);
        decoded_reg_strb.hwpe_job_dep.subtile_nb1 = cpuif_req_masked & (cpuif_addr == 7'h6c);
        decoded_reg_strb.hwpe_job_dep.padding = cpuif_req_masked & (cpuif_addr == 7'h70);
        decoded_reg_strb.hwpe_job_dep.weight_offset = cpuif_req_masked & (cpuif_addr == 7'h74);
        decoded_reg_strb.hwpe_job_dep.filter_mask = cpuif_req_masked & (cpuif_addr == 7'h78);
        decoded_reg_strb.hwpe_job_dep.config0 = cpuif_req_masked & (cpuif_addr == 7'h7c);
        decoded_err = (~is_valid_addr | is_invalid_rw) & decoded_req;
    end

    // Pass down signals to next stage
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                struct {
                    logic [1:0] next;
                    logic load_next;
                } commit_trigger;
            } commit_trigger;
            struct {
                struct {
                    logic [1:0] next;
                    logic load_next;
                } soft_clear;
            } soft_clear;
        } hwpe_ctrl;
        struct {
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } value;
            } weights_ptr;
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } value;
            } infeat_ptr;
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } value;
            } outfeat_ptr;
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } value;
            } scale_ptr;
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } value;
            } scale_shift_ptr;
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } value;
            } scale_bias_ptr;
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } value;
            } infeat_d0_stride;
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } value;
            } infeat_d1_stride;
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } value;
            } infeat_d2_stride;
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } value;
            } outfeat_d0_stride;
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } value;
            } outfeat_d1_stride;
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } value;
            } outfeat_d2_stride;
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } value;
            } weights_d0_stride;
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } value;
            } weights_d1_stride;
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } value;
            } weights_d2_stride;
            struct {
                struct {
                    logic [15:0] next;
                    logic load_next;
                } ki;
                struct {
                    logic [15:0] next;
                    logic load_next;
                } ko;
            } subtile_rem0;
            struct {
                struct {
                    logic [15:0] next;
                    logic load_next;
                } wo;
                struct {
                    logic [15:0] next;
                    logic load_next;
                } ho;
            } subtile_rem1;
            struct {
                struct {
                    logic [15:0] next;
                    logic load_next;
                } wi;
                struct {
                    logic [15:0] next;
                    logic load_next;
                } hi;
            } subtile_rem2;
            struct {
                struct {
                    logic [15:0] next;
                    logic load_next;
                } ki;
                struct {
                    logic [15:0] next;
                    logic load_next;
                } ko;
            } subtile_nb0;
            struct {
                struct {
                    logic [15:0] next;
                    logic load_next;
                } wo;
                struct {
                    logic [15:0] next;
                    logic load_next;
                } ho;
            } subtile_nb1;
            struct {
                struct {
                    logic [15:0] next;
                    logic load_next;
                } value;
                struct {
                    logic [3:0] next;
                    logic load_next;
                } left;
                struct {
                    logic [3:0] next;
                    logic load_next;
                } bottom;
                struct {
                    logic [3:0] next;
                    logic load_next;
                } right;
                struct {
                    logic [3:0] next;
                    logic load_next;
                } top;
            } padding;
            struct {
                struct {
                    logic [31:0] next;
                    logic load_next;
                } value;
            } weight_offset;
            struct {
                struct {
                    logic [7:0] next;
                    logic load_next;
                } left;
                struct {
                    logic [7:0] next;
                    logic load_next;
                } bottom;
                struct {
                    logic [7:0] next;
                    logic load_next;
                } right;
                struct {
                    logic [7:0] next;
                    logic load_next;
                } top;
            } filter_mask;
            struct {
                struct {
                    logic [2:0] next;
                    logic load_next;
                } wbits;
                struct {
                    logic next;
                    logic load_next;
                } reserved2;
                struct {
                    logic next;
                    logic load_next;
                } streamout_quant;
                struct {
                    logic [1:0] next;
                    logic load_next;
                } filter_mode;
                struct {
                    logic [3:0] next;
                    logic load_next;
                } padding;
                struct {
                    logic next;
                    logic load_next;
                } rounding;
                struct {
                    logic [1:0] next;
                    logic load_next;
                } norm_bits;
                struct {
                    logic next;
                    logic load_next;
                } streamin;
                struct {
                    logic next;
                    logic load_next;
                } woffs;
                struct {
                    logic [15:0] next;
                    logic load_next;
                } reserved;
            } config0;
        } hwpe_job_dep;
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                struct {
                    logic [1:0] value;
                } commit_trigger;
            } commit_trigger;
            struct {
                struct {
                    logic [1:0] value;
                } soft_clear;
            } soft_clear;
        } hwpe_ctrl;
        struct {
            struct {
                struct {
                    logic [31:0] value;
                } value;
            } weights_ptr;
            struct {
                struct {
                    logic [31:0] value;
                } value;
            } infeat_ptr;
            struct {
                struct {
                    logic [31:0] value;
                } value;
            } outfeat_ptr;
            struct {
                struct {
                    logic [31:0] value;
                } value;
            } scale_ptr;
            struct {
                struct {
                    logic [31:0] value;
                } value;
            } scale_shift_ptr;
            struct {
                struct {
                    logic [31:0] value;
                } value;
            } scale_bias_ptr;
            struct {
                struct {
                    logic [31:0] value;
                } value;
            } infeat_d0_stride;
            struct {
                struct {
                    logic [31:0] value;
                } value;
            } infeat_d1_stride;
            struct {
                struct {
                    logic [31:0] value;
                } value;
            } infeat_d2_stride;
            struct {
                struct {
                    logic [31:0] value;
                } value;
            } outfeat_d0_stride;
            struct {
                struct {
                    logic [31:0] value;
                } value;
            } outfeat_d1_stride;
            struct {
                struct {
                    logic [31:0] value;
                } value;
            } outfeat_d2_stride;
            struct {
                struct {
                    logic [31:0] value;
                } value;
            } weights_d0_stride;
            struct {
                struct {
                    logic [31:0] value;
                } value;
            } weights_d1_stride;
            struct {
                struct {
                    logic [31:0] value;
                } value;
            } weights_d2_stride;
            struct {
                struct {
                    logic [15:0] value;
                } ki;
                struct {
                    logic [15:0] value;
                } ko;
            } subtile_rem0;
            struct {
                struct {
                    logic [15:0] value;
                } wo;
                struct {
                    logic [15:0] value;
                } ho;
            } subtile_rem1;
            struct {
                struct {
                    logic [15:0] value;
                } wi;
                struct {
                    logic [15:0] value;
                } hi;
            } subtile_rem2;
            struct {
                struct {
                    logic [15:0] value;
                } ki;
                struct {
                    logic [15:0] value;
                } ko;
            } subtile_nb0;
            struct {
                struct {
                    logic [15:0] value;
                } wo;
                struct {
                    logic [15:0] value;
                } ho;
            } subtile_nb1;
            struct {
                struct {
                    logic [15:0] value;
                } value;
                struct {
                    logic [3:0] value;
                } left;
                struct {
                    logic [3:0] value;
                } bottom;
                struct {
                    logic [3:0] value;
                } right;
                struct {
                    logic [3:0] value;
                } top;
            } padding;
            struct {
                struct {
                    logic [31:0] value;
                } value;
            } weight_offset;
            struct {
                struct {
                    logic [7:0] value;
                } left;
                struct {
                    logic [7:0] value;
                } bottom;
                struct {
                    logic [7:0] value;
                } right;
                struct {
                    logic [7:0] value;
                } top;
            } filter_mask;
            struct {
                struct {
                    logic [2:0] value;
                } wbits;
                struct {
                    logic value;
                } reserved2;
                struct {
                    logic value;
                } streamout_quant;
                struct {
                    logic [1:0] value;
                } filter_mode;
                struct {
                    logic [3:0] value;
                } padding;
                struct {
                    logic value;
                } rounding;
                struct {
                    logic [1:0] value;
                } norm_bits;
                struct {
                    logic value;
                } streamin;
                struct {
                    logic value;
                } woffs;
                struct {
                    logic [15:0] value;
                } reserved;
            } config0;
        } hwpe_job_dep;
    } field_storage_t;
    field_storage_t field_storage;

    // Field: neureka_regif.hwpe_ctrl.commit_trigger.commit_trigger
    always_comb begin
        automatic logic [1:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_ctrl.commit_trigger.commit_trigger.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_ctrl.commit_trigger && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_ctrl.commit_trigger.commit_trigger.value & ~decoded_wr_biten[1:0]) | (decoded_wr_data[1:0] & decoded_wr_biten[1:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_ctrl.commit_trigger.commit_trigger.next = next_c;
        field_combo.hwpe_ctrl.commit_trigger.commit_trigger.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_ctrl.commit_trigger.commit_trigger.value <= 2'h0;
        end else begin
            if(field_combo.hwpe_ctrl.commit_trigger.commit_trigger.load_next) begin
                field_storage.hwpe_ctrl.commit_trigger.commit_trigger.value <= field_combo.hwpe_ctrl.commit_trigger.commit_trigger.next;
            end
        end
    end
    assign hwif_out.hwpe_ctrl.commit_trigger.commit_trigger.value = field_storage.hwpe_ctrl.commit_trigger.commit_trigger.value;
    assign hwif_out.hwpe_ctrl.commit_trigger.commit_trigger.swacc = decoded_reg_strb.hwpe_ctrl.commit_trigger;
    assign hwif_out.hwpe_ctrl.commit_trigger.r0.value = 30'h0;
    assign hwif_out.hwpe_ctrl.acquire.acquire.swacc = decoded_reg_strb.hwpe_ctrl.acquire;
    assign hwif_out.hwpe_ctrl.reserved0.reserved.value = 32'h0;
    assign hwif_out.hwpe_ctrl.running_job.r0.value = 24'h0;
    // Field: neureka_regif.hwpe_ctrl.soft_clear.soft_clear
    always_comb begin
        automatic logic [1:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_ctrl.soft_clear.soft_clear.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_ctrl.soft_clear && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_ctrl.soft_clear.soft_clear.value & ~decoded_wr_biten[1:0]) | (decoded_wr_data[1:0] & decoded_wr_biten[1:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_ctrl.soft_clear.soft_clear.next = next_c;
        field_combo.hwpe_ctrl.soft_clear.soft_clear.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_ctrl.soft_clear.soft_clear.value <= 2'h0;
        end else begin
            if(field_combo.hwpe_ctrl.soft_clear.soft_clear.load_next) begin
                field_storage.hwpe_ctrl.soft_clear.soft_clear.value <= field_combo.hwpe_ctrl.soft_clear.soft_clear.next;
            end
        end
    end
    assign hwif_out.hwpe_ctrl.soft_clear.soft_clear.value = field_storage.hwpe_ctrl.soft_clear.soft_clear.value;
    assign hwif_out.hwpe_ctrl.soft_clear.soft_clear.swacc = decoded_reg_strb.hwpe_ctrl.soft_clear;
    assign hwif_out.hwpe_ctrl.soft_clear.r0.value = 30'h0;
    assign hwif_out.hwpe_ctrl.reserved1.reserved.value = 32'h0;
    assign hwif_out.hwpe_ctrl.reserved2.reserved.value = 32'h0;
    // Field: neureka_regif.hwpe_job_dep.weights_ptr.value
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.weights_ptr.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.weights_ptr && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.weights_ptr.value.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.weights_ptr.value.next = next_c;
        field_combo.hwpe_job_dep.weights_ptr.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.weights_ptr.value.value <= 32'h0;
        end else begin
            if(field_combo.hwpe_job_dep.weights_ptr.value.load_next) begin
                field_storage.hwpe_job_dep.weights_ptr.value.value <= field_combo.hwpe_job_dep.weights_ptr.value.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.weights_ptr.value.value = field_storage.hwpe_job_dep.weights_ptr.value.value;
    // Field: neureka_regif.hwpe_job_dep.infeat_ptr.value
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.infeat_ptr.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.infeat_ptr && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.infeat_ptr.value.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.infeat_ptr.value.next = next_c;
        field_combo.hwpe_job_dep.infeat_ptr.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.infeat_ptr.value.value <= 32'h0;
        end else begin
            if(field_combo.hwpe_job_dep.infeat_ptr.value.load_next) begin
                field_storage.hwpe_job_dep.infeat_ptr.value.value <= field_combo.hwpe_job_dep.infeat_ptr.value.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.infeat_ptr.value.value = field_storage.hwpe_job_dep.infeat_ptr.value.value;
    // Field: neureka_regif.hwpe_job_dep.outfeat_ptr.value
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.outfeat_ptr.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.outfeat_ptr && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.outfeat_ptr.value.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.outfeat_ptr.value.next = next_c;
        field_combo.hwpe_job_dep.outfeat_ptr.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.outfeat_ptr.value.value <= 32'h0;
        end else begin
            if(field_combo.hwpe_job_dep.outfeat_ptr.value.load_next) begin
                field_storage.hwpe_job_dep.outfeat_ptr.value.value <= field_combo.hwpe_job_dep.outfeat_ptr.value.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.outfeat_ptr.value.value = field_storage.hwpe_job_dep.outfeat_ptr.value.value;
    // Field: neureka_regif.hwpe_job_dep.scale_ptr.value
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.scale_ptr.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.scale_ptr && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.scale_ptr.value.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.scale_ptr.value.next = next_c;
        field_combo.hwpe_job_dep.scale_ptr.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.scale_ptr.value.value <= 32'h0;
        end else begin
            if(field_combo.hwpe_job_dep.scale_ptr.value.load_next) begin
                field_storage.hwpe_job_dep.scale_ptr.value.value <= field_combo.hwpe_job_dep.scale_ptr.value.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.scale_ptr.value.value = field_storage.hwpe_job_dep.scale_ptr.value.value;
    // Field: neureka_regif.hwpe_job_dep.scale_shift_ptr.value
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.scale_shift_ptr.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.scale_shift_ptr && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.scale_shift_ptr.value.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.scale_shift_ptr.value.next = next_c;
        field_combo.hwpe_job_dep.scale_shift_ptr.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.scale_shift_ptr.value.value <= 32'h0;
        end else begin
            if(field_combo.hwpe_job_dep.scale_shift_ptr.value.load_next) begin
                field_storage.hwpe_job_dep.scale_shift_ptr.value.value <= field_combo.hwpe_job_dep.scale_shift_ptr.value.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.scale_shift_ptr.value.value = field_storage.hwpe_job_dep.scale_shift_ptr.value.value;
    // Field: neureka_regif.hwpe_job_dep.scale_bias_ptr.value
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.scale_bias_ptr.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.scale_bias_ptr && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.scale_bias_ptr.value.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.scale_bias_ptr.value.next = next_c;
        field_combo.hwpe_job_dep.scale_bias_ptr.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.scale_bias_ptr.value.value <= 32'h0;
        end else begin
            if(field_combo.hwpe_job_dep.scale_bias_ptr.value.load_next) begin
                field_storage.hwpe_job_dep.scale_bias_ptr.value.value <= field_combo.hwpe_job_dep.scale_bias_ptr.value.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.scale_bias_ptr.value.value = field_storage.hwpe_job_dep.scale_bias_ptr.value.value;
    // Field: neureka_regif.hwpe_job_dep.infeat_d0_stride.value
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.infeat_d0_stride.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.infeat_d0_stride && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.infeat_d0_stride.value.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.infeat_d0_stride.value.next = next_c;
        field_combo.hwpe_job_dep.infeat_d0_stride.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.infeat_d0_stride.value.value <= 32'h0;
        end else begin
            if(field_combo.hwpe_job_dep.infeat_d0_stride.value.load_next) begin
                field_storage.hwpe_job_dep.infeat_d0_stride.value.value <= field_combo.hwpe_job_dep.infeat_d0_stride.value.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.infeat_d0_stride.value.value = field_storage.hwpe_job_dep.infeat_d0_stride.value.value;
    // Field: neureka_regif.hwpe_job_dep.infeat_d1_stride.value
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.infeat_d1_stride.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.infeat_d1_stride && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.infeat_d1_stride.value.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.infeat_d1_stride.value.next = next_c;
        field_combo.hwpe_job_dep.infeat_d1_stride.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.infeat_d1_stride.value.value <= 32'h0;
        end else begin
            if(field_combo.hwpe_job_dep.infeat_d1_stride.value.load_next) begin
                field_storage.hwpe_job_dep.infeat_d1_stride.value.value <= field_combo.hwpe_job_dep.infeat_d1_stride.value.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.infeat_d1_stride.value.value = field_storage.hwpe_job_dep.infeat_d1_stride.value.value;
    // Field: neureka_regif.hwpe_job_dep.infeat_d2_stride.value
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.infeat_d2_stride.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.infeat_d2_stride && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.infeat_d2_stride.value.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.infeat_d2_stride.value.next = next_c;
        field_combo.hwpe_job_dep.infeat_d2_stride.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.infeat_d2_stride.value.value <= 32'h0;
        end else begin
            if(field_combo.hwpe_job_dep.infeat_d2_stride.value.load_next) begin
                field_storage.hwpe_job_dep.infeat_d2_stride.value.value <= field_combo.hwpe_job_dep.infeat_d2_stride.value.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.infeat_d2_stride.value.value = field_storage.hwpe_job_dep.infeat_d2_stride.value.value;
    // Field: neureka_regif.hwpe_job_dep.outfeat_d0_stride.value
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.outfeat_d0_stride.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.outfeat_d0_stride && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.outfeat_d0_stride.value.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.outfeat_d0_stride.value.next = next_c;
        field_combo.hwpe_job_dep.outfeat_d0_stride.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.outfeat_d0_stride.value.value <= 32'h0;
        end else begin
            if(field_combo.hwpe_job_dep.outfeat_d0_stride.value.load_next) begin
                field_storage.hwpe_job_dep.outfeat_d0_stride.value.value <= field_combo.hwpe_job_dep.outfeat_d0_stride.value.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.outfeat_d0_stride.value.value = field_storage.hwpe_job_dep.outfeat_d0_stride.value.value;
    // Field: neureka_regif.hwpe_job_dep.outfeat_d1_stride.value
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.outfeat_d1_stride.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.outfeat_d1_stride && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.outfeat_d1_stride.value.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.outfeat_d1_stride.value.next = next_c;
        field_combo.hwpe_job_dep.outfeat_d1_stride.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.outfeat_d1_stride.value.value <= 32'h0;
        end else begin
            if(field_combo.hwpe_job_dep.outfeat_d1_stride.value.load_next) begin
                field_storage.hwpe_job_dep.outfeat_d1_stride.value.value <= field_combo.hwpe_job_dep.outfeat_d1_stride.value.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.outfeat_d1_stride.value.value = field_storage.hwpe_job_dep.outfeat_d1_stride.value.value;
    // Field: neureka_regif.hwpe_job_dep.outfeat_d2_stride.value
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.outfeat_d2_stride.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.outfeat_d2_stride && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.outfeat_d2_stride.value.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.outfeat_d2_stride.value.next = next_c;
        field_combo.hwpe_job_dep.outfeat_d2_stride.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.outfeat_d2_stride.value.value <= 32'h0;
        end else begin
            if(field_combo.hwpe_job_dep.outfeat_d2_stride.value.load_next) begin
                field_storage.hwpe_job_dep.outfeat_d2_stride.value.value <= field_combo.hwpe_job_dep.outfeat_d2_stride.value.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.outfeat_d2_stride.value.value = field_storage.hwpe_job_dep.outfeat_d2_stride.value.value;
    // Field: neureka_regif.hwpe_job_dep.weights_d0_stride.value
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.weights_d0_stride.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.weights_d0_stride && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.weights_d0_stride.value.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.weights_d0_stride.value.next = next_c;
        field_combo.hwpe_job_dep.weights_d0_stride.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.weights_d0_stride.value.value <= 32'h0;
        end else begin
            if(field_combo.hwpe_job_dep.weights_d0_stride.value.load_next) begin
                field_storage.hwpe_job_dep.weights_d0_stride.value.value <= field_combo.hwpe_job_dep.weights_d0_stride.value.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.weights_d0_stride.value.value = field_storage.hwpe_job_dep.weights_d0_stride.value.value;
    // Field: neureka_regif.hwpe_job_dep.weights_d1_stride.value
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.weights_d1_stride.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.weights_d1_stride && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.weights_d1_stride.value.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.weights_d1_stride.value.next = next_c;
        field_combo.hwpe_job_dep.weights_d1_stride.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.weights_d1_stride.value.value <= 32'h0;
        end else begin
            if(field_combo.hwpe_job_dep.weights_d1_stride.value.load_next) begin
                field_storage.hwpe_job_dep.weights_d1_stride.value.value <= field_combo.hwpe_job_dep.weights_d1_stride.value.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.weights_d1_stride.value.value = field_storage.hwpe_job_dep.weights_d1_stride.value.value;
    // Field: neureka_regif.hwpe_job_dep.weights_d2_stride.value
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.weights_d2_stride.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.weights_d2_stride && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.weights_d2_stride.value.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.weights_d2_stride.value.next = next_c;
        field_combo.hwpe_job_dep.weights_d2_stride.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.weights_d2_stride.value.value <= 32'h0;
        end else begin
            if(field_combo.hwpe_job_dep.weights_d2_stride.value.load_next) begin
                field_storage.hwpe_job_dep.weights_d2_stride.value.value <= field_combo.hwpe_job_dep.weights_d2_stride.value.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.weights_d2_stride.value.value = field_storage.hwpe_job_dep.weights_d2_stride.value.value;
    // Field: neureka_regif.hwpe_job_dep.subtile_rem0.ki
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.subtile_rem0.ki.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.subtile_rem0 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.subtile_rem0.ki.value & ~decoded_wr_biten[15:0]) | (decoded_wr_data[15:0] & decoded_wr_biten[15:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.subtile_rem0.ki.next = next_c;
        field_combo.hwpe_job_dep.subtile_rem0.ki.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.subtile_rem0.ki.value <= 16'h0;
        end else begin
            if(field_combo.hwpe_job_dep.subtile_rem0.ki.load_next) begin
                field_storage.hwpe_job_dep.subtile_rem0.ki.value <= field_combo.hwpe_job_dep.subtile_rem0.ki.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.subtile_rem0.ki.value = field_storage.hwpe_job_dep.subtile_rem0.ki.value;
    // Field: neureka_regif.hwpe_job_dep.subtile_rem0.ko
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.subtile_rem0.ko.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.subtile_rem0 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.subtile_rem0.ko.value & ~decoded_wr_biten[31:16]) | (decoded_wr_data[31:16] & decoded_wr_biten[31:16]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.subtile_rem0.ko.next = next_c;
        field_combo.hwpe_job_dep.subtile_rem0.ko.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.subtile_rem0.ko.value <= 16'h0;
        end else begin
            if(field_combo.hwpe_job_dep.subtile_rem0.ko.load_next) begin
                field_storage.hwpe_job_dep.subtile_rem0.ko.value <= field_combo.hwpe_job_dep.subtile_rem0.ko.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.subtile_rem0.ko.value = field_storage.hwpe_job_dep.subtile_rem0.ko.value;
    // Field: neureka_regif.hwpe_job_dep.subtile_rem1.wo
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.subtile_rem1.wo.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.subtile_rem1 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.subtile_rem1.wo.value & ~decoded_wr_biten[15:0]) | (decoded_wr_data[15:0] & decoded_wr_biten[15:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.subtile_rem1.wo.next = next_c;
        field_combo.hwpe_job_dep.subtile_rem1.wo.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.subtile_rem1.wo.value <= 16'h0;
        end else begin
            if(field_combo.hwpe_job_dep.subtile_rem1.wo.load_next) begin
                field_storage.hwpe_job_dep.subtile_rem1.wo.value <= field_combo.hwpe_job_dep.subtile_rem1.wo.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.subtile_rem1.wo.value = field_storage.hwpe_job_dep.subtile_rem1.wo.value;
    // Field: neureka_regif.hwpe_job_dep.subtile_rem1.ho
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.subtile_rem1.ho.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.subtile_rem1 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.subtile_rem1.ho.value & ~decoded_wr_biten[31:16]) | (decoded_wr_data[31:16] & decoded_wr_biten[31:16]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.subtile_rem1.ho.next = next_c;
        field_combo.hwpe_job_dep.subtile_rem1.ho.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.subtile_rem1.ho.value <= 16'h0;
        end else begin
            if(field_combo.hwpe_job_dep.subtile_rem1.ho.load_next) begin
                field_storage.hwpe_job_dep.subtile_rem1.ho.value <= field_combo.hwpe_job_dep.subtile_rem1.ho.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.subtile_rem1.ho.value = field_storage.hwpe_job_dep.subtile_rem1.ho.value;
    // Field: neureka_regif.hwpe_job_dep.subtile_rem2.wi
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.subtile_rem2.wi.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.subtile_rem2 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.subtile_rem2.wi.value & ~decoded_wr_biten[15:0]) | (decoded_wr_data[15:0] & decoded_wr_biten[15:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.subtile_rem2.wi.next = next_c;
        field_combo.hwpe_job_dep.subtile_rem2.wi.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.subtile_rem2.wi.value <= 16'h0;
        end else begin
            if(field_combo.hwpe_job_dep.subtile_rem2.wi.load_next) begin
                field_storage.hwpe_job_dep.subtile_rem2.wi.value <= field_combo.hwpe_job_dep.subtile_rem2.wi.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.subtile_rem2.wi.value = field_storage.hwpe_job_dep.subtile_rem2.wi.value;
    // Field: neureka_regif.hwpe_job_dep.subtile_rem2.hi
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.subtile_rem2.hi.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.subtile_rem2 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.subtile_rem2.hi.value & ~decoded_wr_biten[31:16]) | (decoded_wr_data[31:16] & decoded_wr_biten[31:16]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.subtile_rem2.hi.next = next_c;
        field_combo.hwpe_job_dep.subtile_rem2.hi.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.subtile_rem2.hi.value <= 16'h0;
        end else begin
            if(field_combo.hwpe_job_dep.subtile_rem2.hi.load_next) begin
                field_storage.hwpe_job_dep.subtile_rem2.hi.value <= field_combo.hwpe_job_dep.subtile_rem2.hi.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.subtile_rem2.hi.value = field_storage.hwpe_job_dep.subtile_rem2.hi.value;
    // Field: neureka_regif.hwpe_job_dep.subtile_nb0.ki
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.subtile_nb0.ki.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.subtile_nb0 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.subtile_nb0.ki.value & ~decoded_wr_biten[15:0]) | (decoded_wr_data[15:0] & decoded_wr_biten[15:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.subtile_nb0.ki.next = next_c;
        field_combo.hwpe_job_dep.subtile_nb0.ki.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.subtile_nb0.ki.value <= 16'h0;
        end else begin
            if(field_combo.hwpe_job_dep.subtile_nb0.ki.load_next) begin
                field_storage.hwpe_job_dep.subtile_nb0.ki.value <= field_combo.hwpe_job_dep.subtile_nb0.ki.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.subtile_nb0.ki.value = field_storage.hwpe_job_dep.subtile_nb0.ki.value;
    // Field: neureka_regif.hwpe_job_dep.subtile_nb0.ko
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.subtile_nb0.ko.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.subtile_nb0 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.subtile_nb0.ko.value & ~decoded_wr_biten[31:16]) | (decoded_wr_data[31:16] & decoded_wr_biten[31:16]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.subtile_nb0.ko.next = next_c;
        field_combo.hwpe_job_dep.subtile_nb0.ko.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.subtile_nb0.ko.value <= 16'h0;
        end else begin
            if(field_combo.hwpe_job_dep.subtile_nb0.ko.load_next) begin
                field_storage.hwpe_job_dep.subtile_nb0.ko.value <= field_combo.hwpe_job_dep.subtile_nb0.ko.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.subtile_nb0.ko.value = field_storage.hwpe_job_dep.subtile_nb0.ko.value;
    // Field: neureka_regif.hwpe_job_dep.subtile_nb1.wo
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.subtile_nb1.wo.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.subtile_nb1 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.subtile_nb1.wo.value & ~decoded_wr_biten[15:0]) | (decoded_wr_data[15:0] & decoded_wr_biten[15:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.subtile_nb1.wo.next = next_c;
        field_combo.hwpe_job_dep.subtile_nb1.wo.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.subtile_nb1.wo.value <= 16'h0;
        end else begin
            if(field_combo.hwpe_job_dep.subtile_nb1.wo.load_next) begin
                field_storage.hwpe_job_dep.subtile_nb1.wo.value <= field_combo.hwpe_job_dep.subtile_nb1.wo.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.subtile_nb1.wo.value = field_storage.hwpe_job_dep.subtile_nb1.wo.value;
    // Field: neureka_regif.hwpe_job_dep.subtile_nb1.ho
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.subtile_nb1.ho.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.subtile_nb1 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.subtile_nb1.ho.value & ~decoded_wr_biten[31:16]) | (decoded_wr_data[31:16] & decoded_wr_biten[31:16]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.subtile_nb1.ho.next = next_c;
        field_combo.hwpe_job_dep.subtile_nb1.ho.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.subtile_nb1.ho.value <= 16'h0;
        end else begin
            if(field_combo.hwpe_job_dep.subtile_nb1.ho.load_next) begin
                field_storage.hwpe_job_dep.subtile_nb1.ho.value <= field_combo.hwpe_job_dep.subtile_nb1.ho.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.subtile_nb1.ho.value = field_storage.hwpe_job_dep.subtile_nb1.ho.value;
    // Field: neureka_regif.hwpe_job_dep.padding.value
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.padding.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.padding && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.padding.value.value & ~decoded_wr_biten[15:0]) | (decoded_wr_data[15:0] & decoded_wr_biten[15:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.padding.value.next = next_c;
        field_combo.hwpe_job_dep.padding.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.padding.value.value <= 16'h0;
        end else begin
            if(field_combo.hwpe_job_dep.padding.value.load_next) begin
                field_storage.hwpe_job_dep.padding.value.value <= field_combo.hwpe_job_dep.padding.value.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.padding.value.value = field_storage.hwpe_job_dep.padding.value.value;
    // Field: neureka_regif.hwpe_job_dep.padding.left
    always_comb begin
        automatic logic [3:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.padding.left.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.padding && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.padding.left.value & ~decoded_wr_biten[19:16]) | (decoded_wr_data[19:16] & decoded_wr_biten[19:16]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.padding.left.next = next_c;
        field_combo.hwpe_job_dep.padding.left.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.padding.left.value <= 4'h0;
        end else begin
            if(field_combo.hwpe_job_dep.padding.left.load_next) begin
                field_storage.hwpe_job_dep.padding.left.value <= field_combo.hwpe_job_dep.padding.left.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.padding.left.value = field_storage.hwpe_job_dep.padding.left.value;
    // Field: neureka_regif.hwpe_job_dep.padding.bottom
    always_comb begin
        automatic logic [3:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.padding.bottom.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.padding && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.padding.bottom.value & ~decoded_wr_biten[23:20]) | (decoded_wr_data[23:20] & decoded_wr_biten[23:20]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.padding.bottom.next = next_c;
        field_combo.hwpe_job_dep.padding.bottom.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.padding.bottom.value <= 4'h0;
        end else begin
            if(field_combo.hwpe_job_dep.padding.bottom.load_next) begin
                field_storage.hwpe_job_dep.padding.bottom.value <= field_combo.hwpe_job_dep.padding.bottom.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.padding.bottom.value = field_storage.hwpe_job_dep.padding.bottom.value;
    // Field: neureka_regif.hwpe_job_dep.padding.right
    always_comb begin
        automatic logic [3:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.padding.right.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.padding && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.padding.right.value & ~decoded_wr_biten[27:24]) | (decoded_wr_data[27:24] & decoded_wr_biten[27:24]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.padding.right.next = next_c;
        field_combo.hwpe_job_dep.padding.right.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.padding.right.value <= 4'h0;
        end else begin
            if(field_combo.hwpe_job_dep.padding.right.load_next) begin
                field_storage.hwpe_job_dep.padding.right.value <= field_combo.hwpe_job_dep.padding.right.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.padding.right.value = field_storage.hwpe_job_dep.padding.right.value;
    // Field: neureka_regif.hwpe_job_dep.padding.top
    always_comb begin
        automatic logic [3:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.padding.top.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.padding && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.padding.top.value & ~decoded_wr_biten[31:28]) | (decoded_wr_data[31:28] & decoded_wr_biten[31:28]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.padding.top.next = next_c;
        field_combo.hwpe_job_dep.padding.top.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.padding.top.value <= 4'h0;
        end else begin
            if(field_combo.hwpe_job_dep.padding.top.load_next) begin
                field_storage.hwpe_job_dep.padding.top.value <= field_combo.hwpe_job_dep.padding.top.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.padding.top.value = field_storage.hwpe_job_dep.padding.top.value;
    // Field: neureka_regif.hwpe_job_dep.weight_offset.value
    always_comb begin
        automatic logic [31:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.weight_offset.value.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.weight_offset && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.weight_offset.value.value & ~decoded_wr_biten[31:0]) | (decoded_wr_data[31:0] & decoded_wr_biten[31:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.weight_offset.value.next = next_c;
        field_combo.hwpe_job_dep.weight_offset.value.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.weight_offset.value.value <= 32'h0;
        end else begin
            if(field_combo.hwpe_job_dep.weight_offset.value.load_next) begin
                field_storage.hwpe_job_dep.weight_offset.value.value <= field_combo.hwpe_job_dep.weight_offset.value.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.weight_offset.value.value = field_storage.hwpe_job_dep.weight_offset.value.value;
    // Field: neureka_regif.hwpe_job_dep.filter_mask.left
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.filter_mask.left.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.filter_mask && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.filter_mask.left.value & ~decoded_wr_biten[7:0]) | (decoded_wr_data[7:0] & decoded_wr_biten[7:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.filter_mask.left.next = next_c;
        field_combo.hwpe_job_dep.filter_mask.left.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.filter_mask.left.value <= 8'h0;
        end else begin
            if(field_combo.hwpe_job_dep.filter_mask.left.load_next) begin
                field_storage.hwpe_job_dep.filter_mask.left.value <= field_combo.hwpe_job_dep.filter_mask.left.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.filter_mask.left.value = field_storage.hwpe_job_dep.filter_mask.left.value;
    // Field: neureka_regif.hwpe_job_dep.filter_mask.bottom
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.filter_mask.bottom.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.filter_mask && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.filter_mask.bottom.value & ~decoded_wr_biten[15:8]) | (decoded_wr_data[15:8] & decoded_wr_biten[15:8]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.filter_mask.bottom.next = next_c;
        field_combo.hwpe_job_dep.filter_mask.bottom.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.filter_mask.bottom.value <= 8'h0;
        end else begin
            if(field_combo.hwpe_job_dep.filter_mask.bottom.load_next) begin
                field_storage.hwpe_job_dep.filter_mask.bottom.value <= field_combo.hwpe_job_dep.filter_mask.bottom.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.filter_mask.bottom.value = field_storage.hwpe_job_dep.filter_mask.bottom.value;
    // Field: neureka_regif.hwpe_job_dep.filter_mask.right
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.filter_mask.right.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.filter_mask && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.filter_mask.right.value & ~decoded_wr_biten[23:16]) | (decoded_wr_data[23:16] & decoded_wr_biten[23:16]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.filter_mask.right.next = next_c;
        field_combo.hwpe_job_dep.filter_mask.right.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.filter_mask.right.value <= 8'h0;
        end else begin
            if(field_combo.hwpe_job_dep.filter_mask.right.load_next) begin
                field_storage.hwpe_job_dep.filter_mask.right.value <= field_combo.hwpe_job_dep.filter_mask.right.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.filter_mask.right.value = field_storage.hwpe_job_dep.filter_mask.right.value;
    // Field: neureka_regif.hwpe_job_dep.filter_mask.top
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.filter_mask.top.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.filter_mask && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.filter_mask.top.value & ~decoded_wr_biten[31:24]) | (decoded_wr_data[31:24] & decoded_wr_biten[31:24]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.filter_mask.top.next = next_c;
        field_combo.hwpe_job_dep.filter_mask.top.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.filter_mask.top.value <= 8'h0;
        end else begin
            if(field_combo.hwpe_job_dep.filter_mask.top.load_next) begin
                field_storage.hwpe_job_dep.filter_mask.top.value <= field_combo.hwpe_job_dep.filter_mask.top.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.filter_mask.top.value = field_storage.hwpe_job_dep.filter_mask.top.value;
    // Field: neureka_regif.hwpe_job_dep.config0.wbits
    always_comb begin
        automatic logic [2:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.config0.wbits.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.config0 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.config0.wbits.value & ~decoded_wr_biten[2:0]) | (decoded_wr_data[2:0] & decoded_wr_biten[2:0]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.config0.wbits.next = next_c;
        field_combo.hwpe_job_dep.config0.wbits.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.config0.wbits.value <= 3'h0;
        end else begin
            if(field_combo.hwpe_job_dep.config0.wbits.load_next) begin
                field_storage.hwpe_job_dep.config0.wbits.value <= field_combo.hwpe_job_dep.config0.wbits.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.config0.wbits.value = field_storage.hwpe_job_dep.config0.wbits.value;
    // Field: neureka_regif.hwpe_job_dep.config0.reserved2
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.config0.reserved2.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.config0 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.config0.reserved2.value & ~decoded_wr_biten[3:3]) | (decoded_wr_data[3:3] & decoded_wr_biten[3:3]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.config0.reserved2.next = next_c;
        field_combo.hwpe_job_dep.config0.reserved2.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.config0.reserved2.value <= 1'h0;
        end else begin
            if(field_combo.hwpe_job_dep.config0.reserved2.load_next) begin
                field_storage.hwpe_job_dep.config0.reserved2.value <= field_combo.hwpe_job_dep.config0.reserved2.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.config0.reserved2.value = field_storage.hwpe_job_dep.config0.reserved2.value;
    // Field: neureka_regif.hwpe_job_dep.config0.streamout_quant
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.config0.streamout_quant.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.config0 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.config0.streamout_quant.value & ~decoded_wr_biten[4:4]) | (decoded_wr_data[4:4] & decoded_wr_biten[4:4]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.config0.streamout_quant.next = next_c;
        field_combo.hwpe_job_dep.config0.streamout_quant.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.config0.streamout_quant.value <= 1'h0;
        end else begin
            if(field_combo.hwpe_job_dep.config0.streamout_quant.load_next) begin
                field_storage.hwpe_job_dep.config0.streamout_quant.value <= field_combo.hwpe_job_dep.config0.streamout_quant.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.config0.streamout_quant.value = field_storage.hwpe_job_dep.config0.streamout_quant.value;
    // Field: neureka_regif.hwpe_job_dep.config0.filter_mode
    always_comb begin
        automatic logic [1:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.config0.filter_mode.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.config0 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.config0.filter_mode.value & ~decoded_wr_biten[6:5]) | (decoded_wr_data[6:5] & decoded_wr_biten[6:5]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.config0.filter_mode.next = next_c;
        field_combo.hwpe_job_dep.config0.filter_mode.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.config0.filter_mode.value <= 2'h0;
        end else begin
            if(field_combo.hwpe_job_dep.config0.filter_mode.load_next) begin
                field_storage.hwpe_job_dep.config0.filter_mode.value <= field_combo.hwpe_job_dep.config0.filter_mode.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.config0.filter_mode.value = field_storage.hwpe_job_dep.config0.filter_mode.value;
    // Field: neureka_regif.hwpe_job_dep.config0.padding
    always_comb begin
        automatic logic [3:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.config0.padding.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.config0 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.config0.padding.value & ~decoded_wr_biten[10:7]) | (decoded_wr_data[10:7] & decoded_wr_biten[10:7]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.config0.padding.next = next_c;
        field_combo.hwpe_job_dep.config0.padding.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.config0.padding.value <= 4'h0;
        end else begin
            if(field_combo.hwpe_job_dep.config0.padding.load_next) begin
                field_storage.hwpe_job_dep.config0.padding.value <= field_combo.hwpe_job_dep.config0.padding.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.config0.padding.value = field_storage.hwpe_job_dep.config0.padding.value;
    // Field: neureka_regif.hwpe_job_dep.config0.rounding
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.config0.rounding.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.config0 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.config0.rounding.value & ~decoded_wr_biten[11:11]) | (decoded_wr_data[11:11] & decoded_wr_biten[11:11]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.config0.rounding.next = next_c;
        field_combo.hwpe_job_dep.config0.rounding.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.config0.rounding.value <= 1'h0;
        end else begin
            if(field_combo.hwpe_job_dep.config0.rounding.load_next) begin
                field_storage.hwpe_job_dep.config0.rounding.value <= field_combo.hwpe_job_dep.config0.rounding.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.config0.rounding.value = field_storage.hwpe_job_dep.config0.rounding.value;
    // Field: neureka_regif.hwpe_job_dep.config0.norm_bits
    always_comb begin
        automatic logic [1:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.config0.norm_bits.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.config0 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.config0.norm_bits.value & ~decoded_wr_biten[13:12]) | (decoded_wr_data[13:12] & decoded_wr_biten[13:12]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.config0.norm_bits.next = next_c;
        field_combo.hwpe_job_dep.config0.norm_bits.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.config0.norm_bits.value <= 2'h0;
        end else begin
            if(field_combo.hwpe_job_dep.config0.norm_bits.load_next) begin
                field_storage.hwpe_job_dep.config0.norm_bits.value <= field_combo.hwpe_job_dep.config0.norm_bits.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.config0.norm_bits.value = field_storage.hwpe_job_dep.config0.norm_bits.value;
    // Field: neureka_regif.hwpe_job_dep.config0.streamin
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.config0.streamin.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.config0 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.config0.streamin.value & ~decoded_wr_biten[14:14]) | (decoded_wr_data[14:14] & decoded_wr_biten[14:14]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.config0.streamin.next = next_c;
        field_combo.hwpe_job_dep.config0.streamin.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.config0.streamin.value <= 1'h0;
        end else begin
            if(field_combo.hwpe_job_dep.config0.streamin.load_next) begin
                field_storage.hwpe_job_dep.config0.streamin.value <= field_combo.hwpe_job_dep.config0.streamin.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.config0.streamin.value = field_storage.hwpe_job_dep.config0.streamin.value;
    // Field: neureka_regif.hwpe_job_dep.config0.woffs
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.config0.woffs.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.config0 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.config0.woffs.value & ~decoded_wr_biten[15:15]) | (decoded_wr_data[15:15] & decoded_wr_biten[15:15]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.config0.woffs.next = next_c;
        field_combo.hwpe_job_dep.config0.woffs.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.config0.woffs.value <= 1'h0;
        end else begin
            if(field_combo.hwpe_job_dep.config0.woffs.load_next) begin
                field_storage.hwpe_job_dep.config0.woffs.value <= field_combo.hwpe_job_dep.config0.woffs.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.config0.woffs.value = field_storage.hwpe_job_dep.config0.woffs.value;
    // Field: neureka_regif.hwpe_job_dep.config0.reserved
    always_comb begin
        automatic logic [15:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.hwpe_job_dep.config0.reserved.value;
        load_next_c = '0;
        if(decoded_reg_strb.hwpe_job_dep.config0 && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.hwpe_job_dep.config0.reserved.value & ~decoded_wr_biten[31:16]) | (decoded_wr_data[31:16] & decoded_wr_biten[31:16]);
            load_next_c = '1;
        end
        field_combo.hwpe_job_dep.config0.reserved.next = next_c;
        field_combo.hwpe_job_dep.config0.reserved.load_next = load_next_c;
    end
    always_ff @(posedge clk or negedge arst_n) begin
        if(~arst_n) begin
            field_storage.hwpe_job_dep.config0.reserved.value <= 16'h0;
        end else begin
            if(field_combo.hwpe_job_dep.config0.reserved.load_next) begin
                field_storage.hwpe_job_dep.config0.reserved.value <= field_combo.hwpe_job_dep.config0.reserved.next;
            end
        end
    end
    assign hwif_out.hwpe_job_dep.config0.reserved.value = field_storage.hwpe_job_dep.config0.reserved.value;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;

    // Assign readback values to a flattened array
    logic [31:0] readback_array[32];
    assign readback_array[0][1:0] = '0;
    assign readback_array[0][31:2] = (decoded_reg_strb.hwpe_ctrl.commit_trigger && !decoded_req_is_wr) ? 30'h0 : '0;
    assign readback_array[1][31:0] = (decoded_reg_strb.hwpe_ctrl.acquire && !decoded_req_is_wr) ? hwif_in.hwpe_ctrl.acquire.acquire.next : '0;
    assign readback_array[2][31:0] = (decoded_reg_strb.hwpe_ctrl.reserved0 && !decoded_req_is_wr) ? 32'h0 : '0;
    assign readback_array[3][31:0] = (decoded_reg_strb.hwpe_ctrl.status && !decoded_req_is_wr) ? hwif_in.hwpe_ctrl.status.status0.next : '0;
    assign readback_array[4][7:0] = (decoded_reg_strb.hwpe_ctrl.running_job && !decoded_req_is_wr) ? hwif_in.hwpe_ctrl.running_job.running_job.next : '0;
    assign readback_array[4][31:8] = (decoded_reg_strb.hwpe_ctrl.running_job && !decoded_req_is_wr) ? 24'h0 : '0;
    assign readback_array[5][1:0] = '0;
    assign readback_array[5][31:2] = (decoded_reg_strb.hwpe_ctrl.soft_clear && !decoded_req_is_wr) ? 30'h0 : '0;
    assign readback_array[6][31:0] = (decoded_reg_strb.hwpe_ctrl.reserved1 && !decoded_req_is_wr) ? 32'h0 : '0;
    assign readback_array[7][31:0] = (decoded_reg_strb.hwpe_ctrl.reserved2 && !decoded_req_is_wr) ? 32'h0 : '0;
    assign readback_array[8][31:0] = (decoded_reg_strb.hwpe_job_dep.weights_ptr && !decoded_req_is_wr) ? field_storage.hwpe_job_dep.weights_ptr.value.value : '0;
    assign readback_array[9][31:0] = (decoded_reg_strb.hwpe_job_dep.infeat_ptr && !decoded_req_is_wr) ? field_storage.hwpe_job_dep.infeat_ptr.value.value : '0;
    assign readback_array[10][31:0] = (decoded_reg_strb.hwpe_job_dep.outfeat_ptr && !decoded_req_is_wr) ? field_storage.hwpe_job_dep.outfeat_ptr.value.value : '0;
    assign readback_array[11][31:0] = (decoded_reg_strb.hwpe_job_dep.scale_ptr && !decoded_req_is_wr) ? field_storage.hwpe_job_dep.scale_ptr.value.value : '0;
    assign readback_array[12][31:0] = (decoded_reg_strb.hwpe_job_dep.scale_shift_ptr && !decoded_req_is_wr) ? field_storage.hwpe_job_dep.scale_shift_ptr.value.value : '0;
    assign readback_array[13][31:0] = (decoded_reg_strb.hwpe_job_dep.scale_bias_ptr && !decoded_req_is_wr) ? field_storage.hwpe_job_dep.scale_bias_ptr.value.value : '0;
    assign readback_array[14][31:0] = (decoded_reg_strb.hwpe_job_dep.infeat_d0_stride && !decoded_req_is_wr) ? field_storage.hwpe_job_dep.infeat_d0_stride.value.value : '0;
    assign readback_array[15][31:0] = (decoded_reg_strb.hwpe_job_dep.infeat_d1_stride && !decoded_req_is_wr) ? field_storage.hwpe_job_dep.infeat_d1_stride.value.value : '0;
    assign readback_array[16][31:0] = (decoded_reg_strb.hwpe_job_dep.infeat_d2_stride && !decoded_req_is_wr) ? field_storage.hwpe_job_dep.infeat_d2_stride.value.value : '0;
    assign readback_array[17][31:0] = (decoded_reg_strb.hwpe_job_dep.outfeat_d0_stride && !decoded_req_is_wr) ? field_storage.hwpe_job_dep.outfeat_d0_stride.value.value : '0;
    assign readback_array[18][31:0] = (decoded_reg_strb.hwpe_job_dep.outfeat_d1_stride && !decoded_req_is_wr) ? field_storage.hwpe_job_dep.outfeat_d1_stride.value.value : '0;
    assign readback_array[19][31:0] = (decoded_reg_strb.hwpe_job_dep.outfeat_d2_stride && !decoded_req_is_wr) ? field_storage.hwpe_job_dep.outfeat_d2_stride.value.value : '0;
    assign readback_array[20][31:0] = (decoded_reg_strb.hwpe_job_dep.weights_d0_stride && !decoded_req_is_wr) ? field_storage.hwpe_job_dep.weights_d0_stride.value.value : '0;
    assign readback_array[21][31:0] = (decoded_reg_strb.hwpe_job_dep.weights_d1_stride && !decoded_req_is_wr) ? field_storage.hwpe_job_dep.weights_d1_stride.value.value : '0;
    assign readback_array[22][31:0] = (decoded_reg_strb.hwpe_job_dep.weights_d2_stride && !decoded_req_is_wr) ? field_storage.hwpe_job_dep.weights_d2_stride.value.value : '0;
    assign readback_array[23][15:0] = (decoded_reg_strb.hwpe_job_dep.subtile_rem0 && !decoded_req_is_wr) ? field_storage.hwpe_job_dep.subtile_rem0.ki.value : '0;
    assign readback_array[23][31:16] = (decoded_reg_strb.hwpe_job_dep.subtile_rem0 && !decoded_req_is_wr) ? field_storage.hwpe_job_dep.subtile_rem0.ko.value : '0;
    assign readback_array[24][15:0] = (decoded_reg_strb.hwpe_job_dep.subtile_rem1 && !decoded_req_is_wr) ? field_storage.hwpe_job_dep.subtile_rem1.wo.value : '0;
    assign readback_array[24][31:16] = (decoded_reg_strb.hwpe_job_dep.subtile_rem1 && !decoded_req_is_wr) ? field_storage.hwpe_job_dep.subtile_rem1.ho.value : '0;
    assign readback_array[25][15:0] = (decoded_reg_strb.hwpe_job_dep.subtile_rem2 && !decoded_req_is_wr) ? field_storage.hwpe_job_dep.subtile_rem2.wi.value : '0;
    assign readback_array[25][31:16] = (decoded_reg_strb.hwpe_job_dep.subtile_rem2 && !decoded_req_is_wr) ? field_storage.hwpe_job_dep.subtile_rem2.hi.value : '0;
    assign readback_array[26][15:0] = (decoded_reg_strb.hwpe_job_dep.subtile_nb0 && !decoded_req_is_wr) ? field_storage.hwpe_job_dep.subtile_nb0.ki.value : '0;
    assign readback_array[26][31:16] = (decoded_reg_strb.hwpe_job_dep.subtile_nb0 && !decoded_req_is_wr) ? field_storage.hwpe_job_dep.subtile_nb0.ko.value : '0;
    assign readback_array[27][15:0] = (decoded_reg_strb.hwpe_job_dep.subtile_nb1 && !decoded_req_is_wr) ? field_storage.hwpe_job_dep.subtile_nb1.wo.value : '0;
    assign readback_array[27][31:16] = (decoded_reg_strb.hwpe_job_dep.subtile_nb1 && !decoded_req_is_wr) ? field_storage.hwpe_job_dep.subtile_nb1.ho.value : '0;
    assign readback_array[28][15:0] = (decoded_reg_strb.hwpe_job_dep.padding && !decoded_req_is_wr) ? field_storage.hwpe_job_dep.padding.value.value : '0;
    assign readback_array[28][19:16] = (decoded_reg_strb.hwpe_job_dep.padding && !decoded_req_is_wr) ? field_storage.hwpe_job_dep.padding.left.value : '0;
    assign readback_array[28][23:20] = (decoded_reg_strb.hwpe_job_dep.padding && !decoded_req_is_wr) ? field_storage.hwpe_job_dep.padding.bottom.value : '0;
    assign readback_array[28][27:24] = (decoded_reg_strb.hwpe_job_dep.padding && !decoded_req_is_wr) ? field_storage.hwpe_job_dep.padding.right.value : '0;
    assign readback_array[28][31:28] = (decoded_reg_strb.hwpe_job_dep.padding && !decoded_req_is_wr) ? field_storage.hwpe_job_dep.padding.top.value : '0;
    assign readback_array[29][31:0] = (decoded_reg_strb.hwpe_job_dep.weight_offset && !decoded_req_is_wr) ? field_storage.hwpe_job_dep.weight_offset.value.value : '0;
    assign readback_array[30][7:0] = (decoded_reg_strb.hwpe_job_dep.filter_mask && !decoded_req_is_wr) ? field_storage.hwpe_job_dep.filter_mask.left.value : '0;
    assign readback_array[30][15:8] = (decoded_reg_strb.hwpe_job_dep.filter_mask && !decoded_req_is_wr) ? field_storage.hwpe_job_dep.filter_mask.bottom.value : '0;
    assign readback_array[30][23:16] = (decoded_reg_strb.hwpe_job_dep.filter_mask && !decoded_req_is_wr) ? field_storage.hwpe_job_dep.filter_mask.right.value : '0;
    assign readback_array[30][31:24] = (decoded_reg_strb.hwpe_job_dep.filter_mask && !decoded_req_is_wr) ? field_storage.hwpe_job_dep.filter_mask.top.value : '0;
    assign readback_array[31][2:0] = (decoded_reg_strb.hwpe_job_dep.config0 && !decoded_req_is_wr) ? field_storage.hwpe_job_dep.config0.wbits.value : '0;
    assign readback_array[31][3:3] = (decoded_reg_strb.hwpe_job_dep.config0 && !decoded_req_is_wr) ? field_storage.hwpe_job_dep.config0.reserved2.value : '0;
    assign readback_array[31][4:4] = (decoded_reg_strb.hwpe_job_dep.config0 && !decoded_req_is_wr) ? field_storage.hwpe_job_dep.config0.streamout_quant.value : '0;
    assign readback_array[31][6:5] = (decoded_reg_strb.hwpe_job_dep.config0 && !decoded_req_is_wr) ? field_storage.hwpe_job_dep.config0.filter_mode.value : '0;
    assign readback_array[31][10:7] = (decoded_reg_strb.hwpe_job_dep.config0 && !decoded_req_is_wr) ? field_storage.hwpe_job_dep.config0.padding.value : '0;
    assign readback_array[31][11:11] = (decoded_reg_strb.hwpe_job_dep.config0 && !decoded_req_is_wr) ? field_storage.hwpe_job_dep.config0.rounding.value : '0;
    assign readback_array[31][13:12] = (decoded_reg_strb.hwpe_job_dep.config0 && !decoded_req_is_wr) ? field_storage.hwpe_job_dep.config0.norm_bits.value : '0;
    assign readback_array[31][14:14] = (decoded_reg_strb.hwpe_job_dep.config0 && !decoded_req_is_wr) ? field_storage.hwpe_job_dep.config0.streamin.value : '0;
    assign readback_array[31][15:15] = (decoded_reg_strb.hwpe_job_dep.config0 && !decoded_req_is_wr) ? field_storage.hwpe_job_dep.config0.woffs.value : '0;
    assign readback_array[31][31:16] = (decoded_reg_strb.hwpe_job_dep.config0 && !decoded_req_is_wr) ? field_storage.hwpe_job_dep.config0.reserved.value : '0;

    // Reduce the array
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr;
        readback_err = '0;
        readback_data_var = '0;
        for(int i=0; i<32; i++) readback_data_var |= readback_array[i];
        readback_data = readback_data_var;
    end

    assign cpuif_rd_ack = readback_done;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
